# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: prestashop/prestashop:1.7-7.1-apache

pipelines:
  pull-requests:
    '**':
      - step:
          name: PHP CodeSniffer && PHPUnit
          caches:
            - composer
          script:
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install --no-interaction --prefer-dist --dev
            - vendor/bin/phpcs --standard=PSR2 src/ --ignore=src/Migrations
