{*
* 2007-2023 ETS-Soft
*
* NOTICE OF LICENSE
*
* This file is not open source! Each license that you purchased is only available for 1 website only.
* If you want to use this file on more websites (or projects), you need to purchase additional licenses.
* You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please, contact us for extra customization service at an affordable price
*
*  @author ETS-Soft <contact@etssoft.net>
*  @copyright  2007-2023 ETS-Soft
*  @license    Valid for 1 website (or project) for each purchase of license
*  International Registered Trademark & Property of ETS-Soft
*}
<div class="stats-box-info">
	<div class="row margin-15 {if isset($margin_percentage) &&  ($margin_percentage)}row-5-col{/if}">
		<div class="col-lg-3 box-padding-col">
			<div class="box-info js-type-info-stats" data-type="turnover" data-bg="bg-blue">
				<div class="box-inner bg-pink">
					<div class="box-inner-top">
                        <h5 class="box-info-title">{l s='Turnover' mod='ets_affiliatemarketing'}</h5>
						<div class="box-info-content">
							{$score_counter.turnover|escape:'html':'UTF-8'}
						</div>
                    </div>
                    <span>{l s='Total turnover generated by marketing programs ' mod='ets_affiliatemarketing'}</span>
                    
				</div>
			</div>
		</div>
		<div class="col-lg-3 box-padding-col">
			<div class="box-info js-type-info-stats" data-type="reward" data-bg="bg-green">
				<div class="box-inner bg-green">
						<div class="box-inner-top">
                        <h5 class="box-info-title">{l s='Rewards' mod='ets_affiliatemarketing'}</h5>
						<div class="box-info-content">
							{$score_counter.point_reward|escape:'html':'UTF-8'}
						</div>
                    	</div>
                        <span>{l s='Total approved reward value given to customers' mod='ets_affiliatemarketing'}</span>
				</div>
			</div>
		</div>
		{if isset($margin_percentage) && $margin_percentage !== false && $margin_percentage !== '' && $margin_percentage !== NULL}
		<div class="col-lg-3 box-padding-col">
			<div class="box-info js-type-info-stats" data-type="net_profit" data-bg="bg-yellow" >
				<div class="box-inner bg-yellow">
                <div class="box-inner-top">
					<h5 class="box-info-title">{l s='Net profit' mod='ets_affiliatemarketing'}</h5>
					<div class="box-info-content">
						{$score_counter.net_profit|escape:'html':'UTF-8'}
					</div></div>
                    <span>{l s='Total profit you earned from Affiliate marketing programs' mod='ets_affiliatemarketing'}</span>
				</div>
			</div>
		</div>
		{/if}
		<div class="col-lg-3 box-padding-col">
			<div class="box-info js-type-info-stats" data-type="orders" data-bg="bg-orange">
				<div class="box-inner bg-orange">
                    <div class="box-inner-top">
					<h5 class="box-info-title">{l s='Orders' mod='ets_affiliatemarketing'}</h5>
					<div class="box-info-content">
						{$score_counter.orders|escape:'html':'UTF-8'}
					</div></div>
                    <span>{l s='Orders generated by marketing programs' mod='ets_affiliatemarketing'}</span>
				</div>
			</div>
		</div>
		<div class="col-lg-3 box-padding-col">
			<div class="box-info js-type-info-stats" data-type="customers" data-bg="bg-pink">
				<div class="box-inner  bg-blue">
                <div class="box-inner-top">
					<h5 class="box-info-title">{l s='Referral customers' mod='ets_affiliatemarketing'}</h5>
					<div class="box-info-content">
						{$score_counter.customer|escape:'html':'UTF-8'}
					</div></div>
                    <span>{l s='Customers generated by referral programs' mod='ets_affiliatemarketing'}</span>
				</div>
			</div>
		</div>
		<!--<div class="col-lg-2 col-no-padding">
			<div class="box-info js-type-info-stats" data-type="conversion_rate" data-bg="bg-violet" data-toggle="tooltip" title="{l s='The percentage of marketing expense (total reward value) in total cost of the orders generated by the marketing programs within the date range.' mod='ets_affiliatemarketing'}" data-placement="bottom">
				<div class="box-inner">
					<h5 class="box-info-title">{l s='Marketing expense rate' mod='ets_affiliatemarketing'}</h5>
					<div class="box-info-content">
						{$score_counter.conversion_rate|escape:'html':'UTF-8'}%
					</div>
				</div>
			</div>
		</div>-->
	</div>
</div>

<!--<div class="panel eam-position-relative">-->
	
<div class="section-item eam-section-rewards">
	<div class="row margin-15 row-991">
		<div class="col-lg-4 col-xs-4 col-sm-4 plr-15">
			<div class="box-recently-reward">
				<div class="box-header">
					<h5>{l s='Recently rewards' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="{l s='Recently generated rewards from marketing programs' mod='ets_affiliatemarketing'}"></i></h5>
				</div>
				<div class="box-body">
					{if $recently_rewards }        						
                            <table class="table eam-datatables">
                                <tbody>
								       {foreach $recently_rewards as $r}
                                            <tr>
                                                <td>
                                                    {if $r.status == 1}
        												<span class="label-status-validated" title="{l s='Validated' mod='ets_affiliatemarketing'}"><i class="fa fa-check" aria-hidden="true"></i></span>
        											{elseif $r.status == 0}
        												<span class="label-status-pendding" title="{l s='Pending' mod='ets_affiliatemarketing'}"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
        											{elseif $r.status == -1}
        												<span class="label-status-canceled" title="{l s='Canceled' mod='ets_affiliatemarketing'}"><i class="fa fa-times" aria-hidden="true"></i></span>
        											{elseif $r.status == -2}
        												<span class="label-status-expired" title="{l s='Expired' mod='ets_affiliatemarketing'}"><i class="fa fa-times" aria-hidden="true"></i></span>
        											{/if}
                                                </td>
                                                <td>{$r.amount|escape:'html':'UTF-8'}</td>
                                                <td>
                                                	{if !$r.firstname && !$r.lastname}
                                                	<span class="warning-deleted">{l s='User deleted' mod='ets_affiliatemarketing'} (ID: {$r.id_customer|escape:'html':'UTF-8'})</span>
                                                	{else}
                                                	<a href="{$customer_link|escape:'html':'UTF-8'}&viewreward_users=&id_reward_users={$r.id_customer|intval}" title="{l s='View detail' mod='ets_affiliatemarketing'}">{$r.firstname|escape:'html':'UTF-8'} {$r.lastname|escape:'html':'UTF-8'}</a>
                                                	{/if}
                                                </td>
                                                {assign 'class_time' 'label-time-hour'}
                                                {if $r.time_type == 'ms' || $r.time_type == 'second'}
                                                	{assign 'class_time' 'label-time-second'}
                                                {elseif $r.time_type == 'day'}
                                                	{assign 'class_time' 'label-time-day'}
                                                {elseif $r.time_type == 'minute'}
                                                	{assign 'class_time' 'label-time-minute'}
                                                {elseif $r.time_type == 'hour'}
                                                	{assign 'class_time' 'label-time-hour'}
                                                {else}
                                                	{assign 'class_time' 'label-time-hour'}
                                                {/if}
                                                <td class="text-right">
                                                    <span class="label-time {$class_time|escape:'html':'UTF-8'}" style="text-align: left;">
                                                        {$r.time_ago|escape:'html':'UTF-8'}
                                                    </span>
                                                </td>
                                            </tr>  
								   {/foreach}
                            </tbody>
                          </table> 
                          {if count($recently_rewards) >=5} 
                          <div class="view-list-rewards">
						      <a href="{$reward_history_link|escape:'html':'UTF-8'}" title="{l s='View reward history' mod='ets_affiliatemarketing'}">{l s='View more' mod='ets_affiliatemarketing'}<i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
					       </div>
					       {/if}
                    {else}
                    	<div class="eam-box-no-data">{l s='No data found' mod='ets_affiliatemarketing'}</div>    							
					{/if}
					
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-xs-4 col-sm-4 plr-15">
			<div class="stats-data-reward">
				<div class="stats-container">
					<div class="stats-body">
						<div class="stats-loading">
							<div class="loading-text">
								{l s='Loading...' mod='ets_affiliatemarketing'}
							</div>
						</div>
						<div class="box-dashboard line-chart-reward">
							<div class="box-header">
								<h4 class="box-title">{l s='Turnover & reward growth' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="{l s='Turnovers from marketing programs (only succeed payment orders) and approved rewards of customers' mod='ets_affiliatemarketing'}"></i></h4>
								<div class="box-tool">
									<div class="box-tool-timerange box-date-ranger">
										<input type="text" class="ajax-date-range eam_date_ranger_filter" />
										<input type="hidden" class="date_from_reward" value="" />
										<input type="hidden" class="date_to_reward" value="" />
									</div>
									<div class="box-tool-dropdown">
										<div class="dropdown">
									  	<button class="btn-filter-stats dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										  	{if isset($data_stats.distance) && $data_stats.distance <= 5}{l s='This year' mod='ets_affiliatemarketing'}{else}{l s='All time' mod='ets_affiliatemarketing'}{/if}
										</button>
										  <div class="dropdown-menu">
										    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="all_times">{l s='All time' mod='ets_affiliatemarketing'}</a></li>
										    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="this_month">{l s='This month' mod='ets_affiliatemarketing'}</a></li>
										    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="this_year">{l s='This year' mod='ets_affiliatemarketing'}</a></li>
										    <li><a class="dropdown-item js-eam-filter-time-stats-reward show-time-ranger" href="javascript:void(0)" data-value="time_ranger">{l s='Time range' mod='ets_affiliatemarketing'}</a></li>
										  </div>
										</div>
									</div>
								</div>
							</div>
							<div class="box-body">
								<div id="eam_stats_reward_line">
									<svg></svg>
								</div>
							</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-xs-4 col-sm-4 plr-15">
			<div class="stats-data-reward">
                <div class="stats-body">
    				<div class="stats-loading">
    					<div class="loading-text">
    						{l s='Loading...' mod='ets_affiliatemarketing'}
    					</div>
    				</div>
    				<div class="box-dashboard pie-chart-reward">
    					<div class="box-header">
    						<h4 class="box-title">{l s='Reward ratio' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="{l s='The ratio of rewards of marketing programs (approved rewards only)' mod='ets_affiliatemarketing'}"></i></h4>
    						<div class="box-tool">
    							<div class="box-tool-timerange box-date-ranger">
    								<input type="text" class="ajax-date-range eam_date_ranger_filter">
    								<input type="hidden" class="date_from_reward" value="">
    								<input type="hidden" class="date_to_reward" value="">
    							</div>
    							<div class="box-tool-dropdown">
    								<div class="dropdown">
    							  	<button class="btn-filter-stats dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    								  	{if isset($data_stats.distance) && $data_stats.distance <= 5}{l s='This year' mod='ets_affiliatemarketing'}{else}{l s='All time' mod='ets_affiliatemarketing'}{/if}
    								</button>
    								  <div class="dropdown-menu">
    								    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="all_times">{l s='All time' mod='ets_affiliatemarketing'}</a></li>
    								    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="this_month">{l s='This month' mod='ets_affiliatemarketing'}</a></li>
    								    <li><a class="dropdown-item js-eam-filter-time-stats-reward" href="javascript:void(0)" data-value="this_year">{l s='This year' mod='ets_affiliatemarketing'}</a></li>
    								    <li><a class="dropdown-item js-eam-filter-time-stats-reward show-time-ranger" href="javascript:void(0)" data-value="time_ranger">{l s='Time range' mod='ets_affiliatemarketing'}</a></li>
    								  </div>
    								</div>
    							</div>
    						</div>
    					</div>
    					<div class="box-body">
    						<div id="eam-pie-chart-reward">
    							<svg></svg>
    						</div>
    					</div>
    				</div>
                </div>
			</div>
			
		</div>
	</div>
</div>
<!--</div>-->

<div class="row">
	<div class="col-lg-12 px-10">
		<div class="panel eam-position-relative js-eam-dashboard">
			<div class="panel-header">
				<h3 class="panel-title">{l s='Sales & rewards' mod='ets_affiliatemarketing'} </h3>
			</div>
			<div class="panel-bodys pt-0">
				<!-- Nav tabs -->
			  	<ul class="nav nav-pills nav-tabs" role="tablist" id="nav-tab-rank">
			    	<li role="presentation" class="active">
			    		<a href="#recent_orders" aria-controls="tab_recent_orders" role="tab" data-toggle="tab">
			    			<i class="fa fa-fire"></i> {l s='Recent orders' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='Recent orders generated by marketing programs' mod='ets_affiliatemarketing'}"></i>
			    		</a>
			    	</li>
			    	<li role="presentation">
			    		<a href="#best_seller" aria-controls="best_seller_tab" role="tab" data-toggle="tab">
			    			<i class="fa fa-trophy"></i> {l s='Best selling products' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='Best selling products (only calculated for sales generated by one of the 3 marketing programs)' mod='ets_affiliatemarketing'}"></i>
			    		</a>
			    	</li>
			    	<li role="presentation">
			    		<a href="#top_sponsor" aria-controls="top_sponsor" role="tab" data-toggle="tab">
			    			<i class="fa fa-user"></i> {l s='Top sponsors' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='The sponsors successfully invited friends most' mod='ets_affiliatemarketing'}"></i>
			    		</a>
			    	</li>
			    	<li role="presentation">
			    		<a href="#top_affiliate" aria-controls="top_affiliate" role="tab" data-toggle="tab">
			    			<i class="fa fa-share-alt"></i> {l s='Top affiliates' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='The affiliates (sellers) who earn the most commission by selling affiliate products.' mod='ets_affiliatemarketing'}"></i>
			    		</a>
			    	</li>
			    	<li role="presentation">
			    		<a href="#top_customer" aria-controls="top_customer" role="tab" data-toggle="tab">
			    			<i class="fa fa-mortar-board"></i> {l s='Top loyalty customers' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='The customers who earn the most loyalty rewards by shopping on the website.' mod='ets_affiliatemarketing'}"></i></i>
			    		</a>
			    	</li><li role="presentation">
			    		<a href="#top_reward_accounts" aria-controls="top_reward_accounts" role="tab" data-toggle="tab">
			    			<i class="fa fa-flag"></i> {l s='Top reward accounts' mod='ets_affiliatemarketing'} <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='Customers who earn the most rewards (calculated for all 3 marketing programs)' mod='ets_affiliatemarketing'}"></i>
			    		</a>
			    	</li>
			  	</ul>
			  	<!-- Tab panes -->
				  <div class="tab-content">
				    <div role="tabpanel" class="tab-pane active eam-content-tab" id="recent_orders">
						<div class="panel sub-panel">
							
							<div class="panel-body">
								<table class="table">
									<thead>
										<tr>
											<th class="text-left">{l s='Customer Name' mod='ets_affiliatemarketing'}</th>
											<th class="text-center">{l s='Products' mod='ets_affiliatemarketing'}
												<i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='The number of products in each order' mod='ets_affiliatemarketing'}"></i>
											</th>
											<th class="text-center">{l s='Total orders' mod='ets_affiliatemarketing'}
												<i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{l s='Total cost of products containing in marketing programs' mod='ets_affiliatemarketing'}"></i>
											</th>
											<th class="text-center">{l s='Date' mod='ets_affiliatemarketing'}
											</th>
											<th class="text-center">{l s='Status' mod='ets_affiliatemarketing'}</th>
											<th class="text-center">{l s='Action' mod='ets_affiliatemarketing'}</th>
										</tr>
									</thead>
									<tbody>
										{if $recent_orders && $recent_orders.results}
										{foreach $recent_orders.results as $ord}
										<tr>
											<td class="text-left">
												{if $ord.username}
													<a href="{$customer_link|escape:'html':'UTF-8'}&id_reward_users={$ord.id_customer|escape:'html':'UTF-8'}&viewreward_users" title="{l s='View user' mod='ets_affiliatemarketing'}">{$ord.username|escape:'html':'UTF-8'}</a>
												{else}
													<a href="{$customer_link|escape:'html':'UTF-8'}&id_reward_users={$ord.id_customer|escape:'html':'UTF-8'}&viewreward_users" title="{l s='View user' mod='ets_affiliatemarketing'}"><span class="warning-deleted">{l s='User deleted' mod='ets_affiliatemarketing'} ID: ({$ord.id_customer|escape:'html':'UTF-8'})</span></a>
												{/if}
											</td>
											<td class="text-center">{$ord.total_product|escape:'html':'UTF-8'}</td>
											<td class="text-center">{$ord.total_turnover|escape:'html':'UTF-8'}</td>
											<td class="text-center">{$ord.datetime_added|escape:'html':'UTF-8'}</td>
											<td class="text-center">
												{if $ord.state_template == 'cheque'}
													<span class="amb-recent-orders-status amb-awaiting-check-payment">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'payment'}
													<span class="amb-recent-orders-status amb-payment-accepted">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'preparation'}
													<span class="amb-recent-orders-status amb-processing-in-progress">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'shipped'}
													<span class="amb-recent-orders-status amb-shipped">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'order_canceled'}
													<span class="amb-recent-orders-status amb-canceled">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'refund'}
													<span class="amb-recent-orders-status amb-refunded">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'payment_error'}
													<span class="amb-recent-orders-status amb-payment-error">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'outofstock'}
													<span class="amb-recent-orders-status amb-on-backorder-paid">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'bankwire'}
													<span class="amb-recent-orders-status amb-awaiting-bank-wire-payment">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'payment'}
													<span class="amb-recent-orders-status amb-remote-payment-accepted">{$ord.status|escape:'html':'UTF-8'}</span>
												{elseif $ord.state_template == 'cashondelivery'}
													<span class="amb-recent-orders-status amb-awaiting-cash-on-delivery-validation">{$ord.status|escape:'html':'UTF-8'}</span>
												{else}
													<span class="amb-recent-orders-status amb-delivered">{$ord.status|escape:'html':'UTF-8'}</span>
												{/if}                
		                                    </td>
											<td class="text-center">
												<a href="{$customer_link|escape:'html':'UTF-8'}&id_reward_users={$ord.id_customer|escape:'html':'UTF-8'}&viewreward_users" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="{l s='View user' mod='ets_affiliatemarketing'}"><i class="fa fa-search"></i></a>
											</td>
										</tr>
										{/foreach}
										{else}
										<tr>
											<td colspan="100%" class="text-center">{l s='No data found' mod='ets_affiliatemarketing'}</td>
										</tr>
										{/if}
									</tbody>
								</table>
							</div>
						</div>
				    </div>
				    <div role="tabpanel" class="tab-pane eam-content-tab" id="best_seller">
				    	<div class="panel sub-panel">
							
							<div class="panel-body">
								
							</div>
						</div>
				    </div>
				    <div role="tabpanel" class="tab-pane eam-content-tab" id="top_customer">
				    	<div class="panel sub-panel">
							
							<div class="panel-body">
								
							</div>
						</div>
				    </div>
				    <div role="tabpanel" class="tab-pane eam-content-tab" id="top_sponsor">
				    	<div class="panel sub-panel">
							
							<div class="panel-body">
								
							</div>
						</div>
				    </div>
				    <div role="tabpanel" class="tab-pane eam-content-tab" id="top_affiliate">
				    	<div class="panel sub-panel">
							
							<div class="panel-body">
								
							</div>
						</div>
				    </div>
				    <div role="tabpanel" class="tab-pane eam-content-tab" id="top_reward_accounts">
				    	<div class="panel sub-panel">
							
							<div class="panel-body">
								
							</div>
						</div>
				    </div>
				  </div>
				  <div class="filter-rank-dashboard eam-box-filter">
				  	<div class="stat-filter eam-box-filter eam-box-border p-10">
				  		<form id="formFilterRankDashboard" onsubmit="return false;">
				  			<div class="rows" style="margin-top: 15px;">
								<div class="eam_select_filter">
									<label>{l s='Order status' mod='ets_affiliatemarketing'}</label>
									<select name="order_state" class="form-group" style="display: inline-block; width: auto;">
										<option value="">{l s='All' mod='ets_affiliatemarketing'}</option>
										{foreach $order_states as $state}
										<option value="{$state.id_order_state|escape:'html':'UTF-8'}">{$state.name|escape:'html':'UTF-8'}</option>
										{/foreach}
									</select>
								</div>
								<div class="eam_select_filter" style="display: none;">
									<label>{l s='Reward status' mod='ets_affiliatemarketing'}</label>
									<select name="reward_status" class="form-group" style="display: inline-block; width: auto;">
										<option value="">{l s='All' mod='ets_affiliatemarketing'}</option>
										<option value="1">{l s='Approved' mod='ets_affiliatemarketing'}</option>
										<option value="0">{l s='Pending' mod='ets_affiliatemarketing'}</option>
										<option value="-1">{l s='Canceled' mod='ets_affiliatemarketing'}</option>
										<option value="-2">{l s='Expired' mod='ets_affiliatemarketing'}</option>
									</select>
								</div>
								<div class="eam_select_filter col-lg-5">
									<div>
										<label>{l s='Time range' mod='ets_affiliatemarketing'}</label>
										<select name="type_date_filter" class="form-control field-inline">
											<option value="all_times" selected="selected">{l s='All the time' mod='ets_affiliatemarketing'}</option>
											<option value="this_month" >{l s="This month" mod='ets_affiliatemarketing'} - {date('m/Y') nofilter}</option>
											<option value="this_year">{l s="This year" mod='ets_affiliatemarketing'} - {date('Y') nofilter}</option>
											<option value="time_ranger">{l s='Time range' mod='ets_affiliatemarketing'}</option>
										</select>
										<div class="box-date-ranger">
											<input type="text" name="date_range" value="" class="form-control eam_date_ranger_filter">
											<input type="hidden" name="date_from" class="date_from_reward" value="{date('Y-m-01') nofilter}">
											<input type="hidden" name="date_to" class="date_to_reward" value="{date('Y-m-t') nofilter}">
										</div>
									</div>
								</div>
								<div class="eam_action">
									<div class="form-group">
										<button type="submit" class="btn btn-default btn-block"><i class="fa fa-search"></i> {l s='Filter' mod='ets_affiliatemarketing'}</button>
									
										<button type="button" class="btn btn-default btn-block js-btn-reset-form-filter"><i class="fa fa-undo"></i> {l s='Reset' mod='ets_affiliatemarketing'}</button>
									</div>
								</div>
							</div>
				  		</form>
					</div>
				  </div>
			</div>
		</div>
	</div>
</div>
{if !$cronjob_closed_alert && $loyaltyPrograEnabled && $loyaltyRewardAvailability}
    {if !$last_cronjob || $last_cronjob.warning}
        <div class="row">
    	<div class="col-lg-12 px-10">
    		<div class="panel eam-position-relative panel-cronjob-alert">
    		    <div class="panel-header">
    				<h3 class="panel-title">{l s='Cronjob notification' mod='ets_affiliatemarketing'}</h3>
    			</div>    
    		    <div class="panel-bodys pt-0">            
    		        <div class="ets-box-result-cronjob">
    		             <div class="ets-result-cronjob ets-notification-cronjob">
    		                 <div class="ets-content-cronjob ets-content-notification-cronjob">
    		                 <span>{l s='Cronjob didn\'t run in last 12 hours. Please check again cronjob configuration to make sure Cronjob run correctly' mod='ets_affiliatemarketing'}</span>
    		                    <div class="ets-time-cronjob"><a class="bt-ets-view-cronjob" href="{$module_link|escape:'html':'UTF-8'}&tabActive=cronjob_config">{l s='View Cronjob setting here' mod='ets_affiliatemarketing'} <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
    		                 </div> 
    		                 <span class="ets-close-notification js-eam-close-cronjob-alert" title="{l s='Close' mod='ets_affiliatemarketing'}">x</span>  
    		             </div>
                    </div>
        		    </div>      
        		</div> 
        	</div>
        </div>
    {/if}		        
{/if}

<script type="text/javascript">
	var eam_init_data_stats = {$data_stats|json_encode};
	var eam_init_data_pie = {$pie_reward|json_encode};
	var eam_currency_code = "{$eam_currency_code|escape:'html':'UTF-8'}";
</script>